# Generated by Django 3.2.19 on 2025-01-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipation',
            name='seniority',
            field=models.CharField(blank=True, choices=[('Trainee', 'Trainee'), ('Junior', 'Junior'), ('Semi Senior', 'Semi Senior'), ('Senior', 'Senior'), ('Guido', 'Soy Guido Van Rossum')], default='', max_length=100, verbose_name='experiencia'),
        ),
    ]
