repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - '--config=.flake8'
          - '--exclude=.venv,**/migrations/*.py'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.22.2"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "3.2"]
