# Generated by Django 3.2.13 on 2022-07-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycompanies', '0005_company_owner_to_usercompanyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
