# Generated by Django 3.2.12 on 2022-06-07 13:57

from django.db import migrations


def forward(apps, schema_editor):
    Company = apps.get_model('pycompanies', 'Company')
    UserCompanyProfile = apps.get_model('pycompanies', 'UserCompanyProfile')

    user_profiles = [
        UserCompanyProfile(company_id=company_id, user_id=user_id)
        for company_id, user_id in Company.objects.values_list('id', 'owner')
    ]

    UserCompanyProfile.objects.bulk_create(user_profiles)


def backward(apps, schema_editor):
    UserCompanyProfile = apps.get_model('pycompanies', 'UserCompanyProfile')
    UserCompanyProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pycompanies', '0005_remove_company_owner'),
    ]

    operations = [migrations.RunPython(forward, backward)]
