# Generated by Django 3.0.14 on 2021-11-01 16:14

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pycompanies', '0002_company_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='Lugar')),
                ('contact_mail', models.CharField(max_length=255, null=True, verbose_name='Correo electrónico')),
                ('contact_phone', models.CharField(max_length=255, null=True, verbose_name='Teléfono')),
                ('contact_url', models.CharField(max_length=255, null=True, verbose_name='Sitio web')),
                ('experience', models.CharField(choices=[('0', 'Zero'), ('1+', 'One Plus'), ('2+', 'Two Plus'), ('3+', 'Three Plus'), ('5+', 'Five Plus'), ('10+', 'Ten Plus')], max_length=3, verbose_name='Experiencia')),
                ('remoteness', models.CharField(choices=[('REM', 'Remoto'), ('OFC', 'Presencial'), ('HYB', 'Mixto')], max_length=3, verbose_name='Modalidad de trabajo')),
                ('hiring_type', models.CharField(choices=[('EMP', 'Relación de dependencia'), ('MON', 'Monotributista'), ('CSH', 'Contractor short term'), ('CLT', 'Contractor long term'), ('COO', 'Cooperativa de trabajo'), ('GOV', 'Estado'), ('OTH', 'Otra')], max_length=3, verbose_name='Tipo de contratación')),
                ('salary', models.CharField(max_length=255, null=True, verbose_name='Rango salarial')),
                ('description', models.TextField(verbose_name='Sitio web')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rango salarial')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('DEA', 'Desactivada'), ('MOD', 'En moderación'), ('ACT', 'Activa'), ('REJ', 'Rechazada'), ('EXP', 'Caducada')], max_length=3, verbose_name='Estado de la oferta')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('fields_hash', models.CharField(max_length=255, null=True, verbose_name='Hash de la oferta')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pycompanies.Company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_offers', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('tags', taggit_autosuggest.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas')),
            ],
        ),
        migrations.CreateModel(
            name='JobOfferComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto')),
                ('comment_type', models.CharField(choices=[('MOD', 'Moderación'), ('EDT', 'Edición'), ('SPM', 'Spam'), ('INS', 'Información insuficiente'), ('NPR', 'Oferta no relacionada con Python')], max_length=3, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Rango salarial')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_joboffer_comments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('joboffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffers.JobOffer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='joboffer',
            constraint=models.CheckConstraint(check=models.Q(('contact_mail__isnull', False), ('contact_phone__isnull', False), ('contact_url__isnull', False), _connector='OR'), name='joboffers_joboffer_not_all_contact_info_null'),
        ),
        migrations.AddConstraint(
            model_name='joboffer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('remoteness__in', ('HYB', 'OFC')), ('location__isnull', False)), ('remoteness', 'REM'), _connector='OR'), name='joboffers_joboffer_location_not_null_when_not_remote'),
        ),
    ]
