# Generated by Django 3.0.14 on 2021-11-02 20:25

from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('joboffers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='contact_mail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contact_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Etiquetas'),
        ),
    ]
