# Generated by Django 3.2.9 on 2021-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0002_auto_20211102_1725'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='joboffer',
            name='joboffers_joboffer_location_not_null_when_not_remote',
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience',
            field=models.CharField(choices=[('0', '0'), ('1+', '1+'), ('2+', '2+'), ('3+', '3+'), ('5+', '5+'), ('10+', '10+')], max_length=3, verbose_name='Experiencia'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='hiring_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Relación de dependencia'), ('MONOTRIBUTO', 'Monotributista'), ('CONTRACTOR_SHORT', 'Contractor short term'), ('CONTRACTOR_LONG', 'Contractor long term'), ('COOPERATIVE', 'Cooperativa de trabajo'), ('GOVERNMENT', 'Estado'), ('OTHER', 'Otra')], max_length=32, verbose_name='Tipo de contratación'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='remoteness',
            field=models.CharField(choices=[('REMOTE', 'Remoto'), ('IN_OFFICE', 'Presencial'), ('MIXED', 'Mixto')], max_length=32, verbose_name='Modalidad de trabajo'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='state',
            field=models.CharField(choices=[('DEACTIVATED', 'Desactivada'), ('MODERATION', 'En moderación'), ('ACTIVE', 'Activa'), ('REJECTED', 'Rechazada'), ('EXPIRED', 'Caducada')], default='DEACTIVATED', max_length=32, verbose_name='Estado de la oferta'),
        ),
        migrations.AlterField(
            model_name='joboffercomment',
            name='comment_type',
            field=models.CharField(choices=[('MODERATION', 'Moderación'), ('EDITION', 'Edición'), ('SPAM', 'Spam'), ('INSUFICIENT', 'Información insuficiente'), ('NOT_PYTHON', 'Oferta no relacionada con Python')], max_length=32, verbose_name='Tipo'),
        ),
        migrations.AddConstraint(
            model_name='joboffer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('remoteness__in', ('MIXED', 'IN_OFFICE')), ('location__isnull', False)), ('remoteness', 'REMOTE'), _connector='OR'), name='joboffers_joboffer_location_not_null_when_not_remote'),
        ),
    ]
