# Generated by Django 3.2.11 on 2022-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0015_auto_20201019_1217'),
        ('joboffers', '0007_auto_20220216_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferHistory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('easyaudit.crudevent',),
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='fields_hash',
        ),
    ]
