# Generated by Django 3.2.11 on 2022-03-09 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0008_auto_20220304_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Descripción'),
        ),
    ]
