# Generated by Django 3.2.11 on 2022-03-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0009_alter_joboffer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='JobOfferVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month_and_year', models.PositiveIntegerField()),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Listing View'), (1, 'Detail View'), (2, 'Contact Info View')], verbose_name='Tipo de Evento')),
                ('session', models.CharField(max_length=40, verbose_name='Identificador de Sesión')),
                ('joboffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joboffers.joboffer')),
            ],
        ),
    ]
