# Generated by Django 3.2.11 on 2022-04-05 13:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0010_auto_20220311_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffervisualization',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='joboffervisualization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
