# Generated by Django 3.2.12 on 2022-04-13 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0010_auto_20220311_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobOfferVisualization',
            new_name='JobOfferAccessLog',
        ),
    ]
