# Generated by Django 3.2.12 on 2022-04-13 19:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0011_rename_joboffervisualization_jobofferaccesslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobofferaccesslog',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='jobofferaccesslog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobofferaccesslog',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Visualización en Listado'), (1, 'Visualización de la oferta completa'), (2, 'Apertura de la información de contacto')], verbose_name='Tipo de Evento'),
        ),
    ]
