# Generated by Django 3.2.12 on 2022-06-02 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0012_auto_20220413_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Título'),
        ),
    ]
