# Generated by Django 3.2.12 on 2022-06-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0013_alter_joboffer_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobofferaccesslog',
            options={},
        ),
    ]
