# Generated by Django 3.2.12 on 2022-06-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pycompanies', '0005_company_owner_to_usercompanyprofile'),
        ('joboffers', '0014_alter_jobofferaccesslog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pycompanies.company', verbose_name='Empresa'),
        ),
    ]
