# Generated by Django 3.2.12 on 2022-06-13 17:30

from django.db import migrations


def forward(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    TaggedItem = apps.get_model('taggit', 'TaggedItem')

    job_content_type = ContentType.objects.get(app_label='jobs', model='job')
    joboffer_content_type = ContentType.objects.get(app_label='joboffers',
                                                    model='joboffer')

    tagged_items = TaggedItem.objects.filter(content_type=job_content_type)

    new_tags = [
        TaggedItem(content_type=joboffer_content_type,
                   object_id=tagged_item.object_id,
                   tag=tagged_item.tag) for tagged_item in tagged_items
    ]
    for new_tag in new_tags:
        new_tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0016_migrate_old_jobs'),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
