# Generated by Django 3.2.12 on 2022-06-13 17:30

from django.db import migrations


def forward(apps, schema_editor):
    JobInactivated = apps.get_model('jobs', 'jobinactivated')
    JobOfferComment = apps.get_model('joboffers', 'joboffercomment')

    User = apps.get_model('auth', 'User')

    superuser = User.objects.filter(is_superuser=True).first()

    for old_comment in JobInactivated.objects.filter(
            job__company__isnull=False):
        new_comment = JobOfferComment(
            text=f"{old_comment.reason}: {old_comment.comment}",
            comment_type='MODERATION',
            created_at=old_comment.created,
            created_by=superuser,
            joboffer_id=old_comment.job_id)

        new_comment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('joboffers', '0017_migrate_old_jobs_tags'),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
