name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres2:
        # Docker Hub image
        image: postgres:11.5
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: somepassword
          POSTGRES_DB: testing_db
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [3.9]
    env:
      DJANGO: 1.8 
      SECRET_KEY: supersecret
      DB_PORT: 5432 
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: somepassword
      POSTGRES_USER: postgres
      POSTGRES_DB: testing_db
      DJANGO_SETTINGS_MODULE: pyarweb.settings.development
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system libraries
        run: |
          sudo apt-get install -y libpq-dev libxml2-dev libxslt1-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_requirements.txt
      - name: Lint with flake8
        run: |
          flake8
      - name: Run tests
        run: |
          python3 manage.py test -v2 --noinput
